Feature: Oscillating patterns
  Scenario: Blinker
    Given we have a game:
      """
      .....
      ..O..
      ..O..
      ..O..
      .....
      """
    When we advance the game
    Then the game state is:
      """
      .....
      .....
      .OOO.
      .....
      .....
      """

    Given we have a game:
      """
      .....
      .....
      .OOO.
      .....
      .....
      """
    When we advance the game
    Then the game state is:
      """
      .....
      ..O..
      ..O..
      ..O..
      .....
      """

  Scenario: Blinker
    Given we have a game:
      """
      ......
      ...O..
      .O..O.
      .O..O.
      ..O...
      ......
      """
    When we advance the game
    Then the game state is:
      """
      ......
      ......
      ..OOO.
      .OOO..
      ......
      ......
      """
    When we advance the game
    Then the game state is:
      """
      ......
      ...O..
      .O..O.
      .O..O.
      ..O...
      ......
      """

  Scenario: Beacon
    Given we have a game:
      """
      ......
      .OO...
      .O....
      ....O.
      ...OO.
      ......
      """
    When we advance the game
    Then the game state is:
      """
      ......
      .OO...
      .OO...
      ...OO.
      ...OO.
      ......
      """
    When we advance the game
    Then the game state is:
      """
      ......
      .OO...
      .O....
      ....O.
      ...OO.
      ......
      """
